name: cd

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  info:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          ref: ${{ github.ref_name }}
      - name: Install subfinder
        run: |
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Run script
        run: |
          sudo apt update
          sudo apt install openssl
          chmod +x ./src/*.sh ./main.sh
          ./main.sh acquisory.com ./targets/acquisory.com
          ./main.sh asyncawake.studio ./targets/asyncawakestudio
          ./main.sh ayushmanchhabra.com ./targets/ayushmanchhabra
          ./main.sh vaultfol.io ./targets/vaultfolio
          ./main.sg bikedekho.com,cardekho.com,channelpartnerutility.com,gaadi.com,girnarsoft.co.in,revv.co.in,rupyy.com,zigwheels.com ./targets/girnarsoft

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: refresh domain info"
            git push origin HEAD:${{ github.ref_name }}
          fi
